# Generated by Django 3.2.18 on 2023-03-29 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='medicine_exp',
            new_name='medicine',
        ),
    ]
